# Generated by Django 4.2.4 on 2023-11-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_project_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.TextField(default='Write about this project'),
        ),
    ]
