# Generated by Django 4.2.4 on 2023-11-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_project_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approach',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='goals',
            field=models.TextField(default='Write about the goals of this project'),
        ),
    ]
