# Generated by Django 4.2.4 on 2023-11-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_project_approach_project_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='topic',
            field=models.TextField(default=''),
        ),
    ]
