# Generated by Django 4.2.4 on 2023-11-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='color',
            field=models.CharField(default='black', max_length=100),
        ),
    ]
