# Generated by Django 4.2.4 on 2023-11-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_alter_project_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='topic',
        ),
    ]
