# Generated by Django 4.2.4 on 2023-11-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_project_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='approach',
            field=models.TextField(default=' '),
        ),
    ]
